version: '3'
services:
  redis-server:
    image: "redis"
    ports:
      - "6379:6379"
  node-app:
    build: .
    restart: always
    environment:
      REDIS_HOST: redis-server:6379
    ports:
      - "80:5000"
volumes:
  mysql-data: